[helpers]

[default]
depends = []

[default.files]
"copyq-commands.ini" = "~/AppData/Roaming/copyq/copyq-commands.ini"
"copyq.ini" = "~/AppData/Roaming/copyq/copyq.ini"
"tridactylrc" = "~/.tridactylrc"
"init.vim" = { target = "~/AppData/Local/nvim/init.vim", type = "symbolic" }
"init.first.vim" = { target = "~/AppData/Local/nvim/init.first.vim", type = "symbolic" }
"init.plugins.vim" = { target = "~/AppData/Local/nvim/init.plugins.vim", type = "symbolic" }

[default.variables]
